name: Add label to PR with CI results
description: Add label to PR with CI results
inputs:
  SUCCESS:
    description: Text of the comment
    required: true
  PULL_REQUEST_NUMBER:
    description: Pull request id
    required: false
    default: "0"
  TOKEN:
    description: Pull request id
    required: false
    default: "0"
runs:
  using: "composite"
  steps:
    - name: Check PR labels action step
      id: check_success_label
      run: echo "TEST_COMPLETED=$( echo gh pr list --label 'CI run has succeded!' | grep -o ${{ inputs.PULL_REQUEST_NUMBER }})" >> $GITHUB_ENV
      shell: sh
    - name: See result
      run: echo "${{ env.TEST_COMPLETED }}"
      shell: sh
    - name: See result
      run: echo "${{ env.TEST_COMPLETED == inputs.PULL_REQUEST_NUMBER }}"
      shell: sh
    
    - name: Check PR labels action step
      id: check_fail_label
      run: |
        echo ${{ inputs.TOKEN }} | gh auth login --with-token
        result=$(gh pr list --label "CI run has failed!")
        echo $result
        result=${echo $result | grep -o ${{ inputs.PULL_REQUEST_NUMBER }}}
        echo ""::set-output name=fail_id::$result"
      shell: sh
    - name: See result
      run: echo "${{ steps.check_fail_label.outputs.fail_id == inputs.PULL_REQUEST_NUMBER }}"
      shell: sh

    - name: delete success label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
          labels: "CI run has succeded!"
          number: ${{ inputs.PULL_REQUEST_NUMBER }}
    - name: delete fail label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
          labels: "CI run has failed!"
          number: ${{ inputs.PULL_REQUEST_NUMBER }}
    - name: adding success label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ inputs.SUCCESS == 'true' }}
      with:
          labels: "CI run has succeded!"
          number: ${{ inputs.PULL_REQUEST_NUMBER }}
    - name: adding fail label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ inputs.SUCCESS == 'false' }}
      with:
          labels: "CI run has failed!"
          number: ${{ inputs.PULL_REQUEST_NUMBER }}
