name: Upload Crowdin files

# on any push to main, we upload the translations to be translated
on:
  push:
    branches:
      - main

jobs:
  upload-to-crowdin:
    name: Upload sources to Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Synchronize
        uses: crowdin/github-action@6259628693db7fdaec0770d57d414ca0d64cfde8 # v1.4.12
        with:
          upload_sources: true
          download_translations: false
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
